### ISSUE TITLE
DRF 3.7.4+ compatibility

### ISSUE THREAD

**Issue by nanuxbe** [drf-forms/drf-schema-adapter#30]
It seems DRF added new features to the `@list` and `@detail` decorators.

DRF-Schema-Adapter need to add those as well.

Errors examples:

```
File "/var/lib/jenkins/jobs/Birds.ai-staging/workspace/venv/local/lib/python2.7/site-packages/rest_framework/routers.py", line 207, in _get_dynamic_route
    url_path = escape_curly_brackets(action.url_path)
AttributeError: 'function' object has no attribute 'url_path'
```

```
(venv) patrick@patrick-birds-ai:~/Documents/view/back$ python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fc1044cd9b0>
Traceback (most recent call last):
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/patrick/Documents/view/back/NEST/urls.py", line 52, in <module>
    url(r'api/v2/', include(router_v2.urls)),
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/rest_framework/routers.py", line 101, in urls
    self._urls = self.get_urls()
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/rest_framework/routers.py", line 363, in get_urls
    urls = super(DefaultRouter, self).get_urls()
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/rest_framework/routers.py", line 261, in get_urls
    routes = self.get_routes(viewset)
  File "/home/patrick/Documents/view/venv/local/lib/python2.7/site-packages/rest_framework/routers.py", line 176, in get_routes
    extra_actions = viewset.get_extra_actions()
AttributeError: type object 'UserViewSet' has no attribute 'get_extra_actions'
```

**Comment by nanuxbe** [comment]
fixed by v0.9.54
